os:
    - linux
    - osx

dist: xenial

sudo: required

language: cpp

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i 's/\<libtins\-dev\>//g' resources/install_dependencies.sh; fi
    - ./resources/install_dependencies.sh

script:
    - ./build.sh --non-interactive
    - ./run_tests
